<a href="https://colab.research.google.com/github/yrhutu21/Deep_Learning_Projects/blob/main/Iris_Training_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

In [ ]:
dt = load_iris()

In [ ]:
dt.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
X,Y = dt.data,dt.target

In [ ]:
dt.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
#i/p layer 4 and hidden layer 30 # hidden layer 30 and 10 #hidden layer 10 and o/p layer 3
model = nn.Sequential (
    nn.Linear(4, 30),
    nn.ReLU(),
    nn.Linear(30, 10),
    nn.ReLU(),
    nn.Linear(10, 3),
    #nn.Softmax(dim = 1)
)

In [ ]:
X = torch.FloatTensor(X)
Y = torch.LongTensor(Y)

In [ ]:
#model(X)

tensor([[0.2524, 0.4392, 0.3083],
        [0.2511, 0.4386, 0.3104],
        [0.2521, 0.4382, 0.3097],
        [0.2518, 0.4410, 0.3072],
        [0.2521, 0.4395, 0.3084],
        [0.2521, 0.4446, 0.3034],
        [0.2515, 0.4405, 0.3080],
        [0.2522, 0.4408, 0.3069],
        [0.2518, 0.4398, 0.3084],
        [0.2512, 0.4394, 0.3094],
        [0.2527, 0.4404, 0.3069],
        [0.2520, 0.4424, 0.3056],
        [0.2515, 0.4383, 0.3101],
        [0.2518, 0.4352, 0.3130],
        [0.2538, 0.4351, 0.3110],
        [0.2513, 0.4451, 0.3036],
        [0.2529, 0.4382, 0.3089],
        [0.2524, 0.4396, 0.3079],
        [0.2517, 0.4429, 0.3054],
        [0.2519, 0.4415, 0.3066],
        [0.2501, 0.4415, 0.3084],
        [0.2520, 0.4418, 0.3062],
        [0.2510, 0.4371, 0.3119],
        [0.2512, 0.4423, 0.3065],
        [0.2503, 0.4454, 0.3044],
        [0.2494, 0.4400, 0.3106],
        [0.2519, 0.4428, 0.3054],
        [0.2524, 0.4406, 0.3069],
        [0.2527, 0.4390, 0.3083],
        [0.2514, 0.4420, 0.3065],
        [0.2505, 0.4412, 0.3083],
        [0.2516, 0.4404, 0.3080],
        [0.2503, 0.4453, 0.3044],
        [0.2516, 0.4420, 0.3064],
        [0.2510, 0.4399, 0.3091],
        [0.2529, 0.4360, 0.3111],
        [0.2535, 0.4369, 0.3096],
        [0.2519, 0.4393, 0.3088],
        [0.2516, 0.4386, 0.3098],
        [0.2524, 0.4407, 0.3070],
        [0.2524, 0.4382, 0.3094],
        [0.2491, 0.4361, 0.3148],
        [0.2514, 0.4387, 0.3098],
        [0.2535, 0.4425, 0.3040],
        [0.2522, 0.4467, 0.3010],
        [0.2513, 0.4394, 0.3093],
        [0.2519, 0.4425, 0.3056],
        [0.2517, 0.4399, 0.3084],
        [0.2525, 0.4406, 0.3069],
        [0.2524, 0.4393, 0.3083],
        [0.2431, 0.4726, 0.2843],
        [0.2444, 0.4707, 0.2849],
        [0.2439, 0.4751, 0.2810],
        [0.2462, 0.4678, 0.2861],
        [0.2449, 0.4730, 0.2821],
        [0.2449, 0.4713, 0.2838],
        [0.2445, 0.4728, 0.2827],
        [0.2459, 0.4592, 0.2949],
        [0.2439, 0.4720, 0.2841],
        [0.2466, 0.4655, 0.2879],
        [0.2461, 0.4627, 0.2912],
        [0.2459, 0.4679, 0.2862],
        [0.2451, 0.4669, 0.2881],
        [0.2447, 0.4733, 0.2820],
        [0.2470, 0.4606, 0.2924],
        [0.2437, 0.4698, 0.2865],
        [0.2450, 0.4716, 0.2834],
        [0.2438, 0.4666, 0.2895],
        [0.2469, 0.4734, 0.2797],
        [0.2448, 0.4656, 0.2896],
        [0.2459, 0.4747, 0.2795],
        [0.2448, 0.4662, 0.2890],
        [0.2462, 0.4764, 0.2774],
        [0.2444, 0.4727, 0.2829],
        [0.2438, 0.4692, 0.2870],
        [0.2438, 0.4703, 0.2859],
        [0.2445, 0.4744, 0.2811],
        [0.2451, 0.4770, 0.2780],
        [0.2450, 0.4718, 0.2832],
        [0.2446, 0.4607, 0.2947],
        [0.2451, 0.4649, 0.2900],
        [0.2447, 0.4636, 0.2917],
        [0.2445, 0.4654, 0.2901],
        [0.2463, 0.4782, 0.2756],
        [0.2452, 0.4716, 0.2833],
        [0.2457, 0.4697, 0.2845],
        [0.2439, 0.4732, 0.2829],
        [0.2458, 0.4715, 0.2827],
        [0.2449, 0.4665, 0.2886],
        [0.2456, 0.4673, 0.2871],
        [0.2453, 0.4704, 0.2843],
        [0.2443, 0.4721, 0.2835],
        [0.2447, 0.4667, 0.2886],
        [0.2457, 0.4597, 0.2946],
        [0.2450, 0.4687, 0.2862],
        [0.2437, 0.4677, 0.2886],
        [0.2443, 0.4683, 0.2874],
        [0.2440, 0.4692, 0.2868],
        [0.2479, 0.4549, 0.2972],
        [0.2446, 0.4675, 0.2878],
        [0.2476, 0.4884, 0.2640],
        [0.2474, 0.4793, 0.2733],
        [0.2465, 0.4867, 0.2668],
        [0.2464, 0.4831, 0.2706],
        [0.2472, 0.4861, 0.2666],
        [0.2464, 0.4931, 0.2605],
        [0.2477, 0.4734, 0.2788],
        [0.2459, 0.4895, 0.2646],
        [0.2473, 0.4857, 0.2669],
        [0.2460, 0.4887, 0.2653],
        [0.2456, 0.4786, 0.2758],
        [0.2470, 0.4811, 0.2719],
        [0.2465, 0.4831, 0.2704],
        [0.2483, 0.4792, 0.2725],
        [0.2489, 0.4807, 0.2704],
        [0.2472, 0.4812, 0.2716],
        [0.2458, 0.4819, 0.2722],
        [0.2444, 0.4927, 0.2629],
        [0.2482, 0.4973, 0.2545],
        [0.2474, 0.4780, 0.2746],
        [0.2466, 0.4852, 0.2682],
        [0.2474, 0.4776, 0.2750],
        [0.2467, 0.4941, 0.2593],
        [0.2465, 0.4771, 0.2764],
        [0.2458, 0.4842, 0.2699],
        [0.2450, 0.4861, 0.2689],
        [0.2462, 0.4759, 0.2778],
        [0.2458, 0.4764, 0.2778],
        [0.2475, 0.4844, 0.2681],
        [0.2448, 0.4840, 0.2712],
        [0.2463, 0.4882, 0.2654],
        [0.2435, 0.4892, 0.2673],
        [0.2478, 0.4847, 0.2674],
        [0.2454, 0.4776, 0.2770],
        [0.2462, 0.4822, 0.2716],
        [0.2467, 0.4893, 0.2640],
        [0.2469, 0.4841, 0.2690],
        [0.2456, 0.4817, 0.2726],
        [0.2458, 0.4755, 0.2787],
        [0.2461, 0.4819, 0.2720],
        [0.2473, 0.4849, 0.2679],
        [0.2476, 0.4792, 0.2732],
        [0.2474, 0.4793, 0.2733],
        [0.2468, 0.4870, 0.2662],
        [0.2471, 0.4857, 0.2672],
        [0.2472, 0.4810, 0.2719],
        [0.2475, 0.4788, 0.2737],
        [0.2463, 0.4799, 0.2738],
        [0.2471, 0.4815, 0.2714],
        [0.2461, 0.4782, 0.2756]], grad_fn=<SoftmaxBackward0>)

In [ ]:
#torch.argmax(model(X) , dim=1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1])

In [ ]:
lossfn = nn.CrossEntropyLoss()
optSgd = optim.SGD(model.parameters(), lr =0.01)

Training

In [ ]:
for _ in range(200):
    optSgd.zero_grad()
    Yp = model(X)
    loss = lossfn(Yp, Y)
    loss.backward()
    optSgd.step()

    print(loss.item())

1.132391333580017
1.1239960193634033
1.1171371936798096
1.111205816268921
1.1057120561599731
1.1006332635879517
1.096120834350586
1.0921998023986816
1.0885919332504272
1.085184097290039
1.081929326057434
1.0788114070892334
1.0758142471313477
1.0729341506958008
1.0701429843902588
1.0674386024475098
1.064823865890503
1.0622756481170654
1.0597867965698242
1.057357907295227
1.0549782514572144
1.0526466369628906
1.0503562688827515
1.0481058359146118
1.0458908081054688
1.0437067747116089
1.0415505170822144
1.0394165515899658
1.0373058319091797
1.0352157354354858
1.0331428050994873
1.031084656715393
1.0290391445159912
1.027005672454834
1.024979829788208
1.0229641199111938
1.020954966545105
1.018949270248413
1.0169459581375122
1.0149457454681396
1.0129469633102417
1.0109463930130005
1.0089436769485474
1.006937861442566
1.004928708076477
1.0029140710830688
1.0008924007415771
0.9988630414009094
0.9968249797821045
0.9947797656059265
0.9927238821983337
0.9906573295593262
0.9885814189910889
0.9865086674690247
0.9844295382499695
0.9823430180549622
0.9802432060241699
0.9781284332275391
0.9760012626647949
0.973863959312439
0.9717155694961548
0.9695447683334351
0.9673509001731873
0.9651325345039368
0.9628870487213135
0.9606168866157532
0.9583175778388977
0.9559910893440247
0.953639030456543
0.9512543678283691
0.9488414525985718
0.9463984370231628
0.9439233541488647
0.941417932510376
0.9388844966888428
0.9363186359405518
0.9337247610092163
0.931099534034729
0.9284542798995972
0.9257845282554626
0.9230818748474121
0.9203469753265381
0.9175825715065002
0.9147906303405762
0.9119710326194763
0.90911865234375
0.9062486886978149
0.9033576250076294
0.9004554152488708
0.8975585699081421
0.8946625590324402
0.8917552828788757
0.8888309001922607
0.8858950734138489
0.8829575777053833
0.8800102472305298
0.8770386576652527
0.8740646243095398
0.8710693120956421
0.8680636882781982
0.865051805973053
0.8620377779006958
0.8590105175971985
0.8559689521789551
0.8529183864593506
0.849855899810791
0.8467836976051331
0.8437097072601318
0.8406292796134949
0.837532103061676
0.8344212174415588
0.8313016891479492
0.8281691670417786
0.8250250816345215
0.8218693733215332
0.8187101483345032
0.8155453205108643
0.8123697638511658
0.8091930747032166
0.8060128092765808
0.8028243780136108
0.7996355295181274
0.7964414954185486
0.7932414412498474
0.7900378108024597
0.7868239283561707
0.7836182117462158
0.7804152369499207
0.7772107720375061
0.7740074992179871
0.770801842212677
0.7676014304161072
0.7644122838973999
0.7612407803535461
0.7580737471580505
0.7549177408218384
0.7517785429954529
0.7486459016799927
0.7455206513404846
0.7424030303955078
0.7392947673797607
0.7361986041069031
0.7331117391586304
0.7300335764884949
0.7269643545150757
0.7239038348197937
0.7208536863327026
0.717814028263092
0.7147894501686096
0.7117813229560852
0.7087862491607666
0.7058046460151672
0.702836275100708
0.6998827457427979
0.6969442367553711
0.6940224170684814
0.6911199688911438
0.6882344484329224
0.6853694915771484
0.6825222969055176
0.6796965003013611
0.6768908500671387
0.6741043329238892
0.6713381409645081
0.6685916781425476
0.6658647060394287
0.6631578803062439
0.6604719758033752
0.657808244228363
0.6551638245582581
0.65254145860672
0.6499419212341309
0.6473648548126221
0.6448096036911011
0.6422793865203857
0.6397706270217896
0.6372855305671692
0.6348210573196411
0.6323781609535217
0.6299554109573364
0.6275531053543091
0.6251721978187561
0.6228134036064148
0.6204811334609985
0.6181725263595581
0.6158841848373413
0.613616406917572
0.6113708019256592
0.6091461777687073
0.6069425344467163
0.604762077331543
0.6026023626327515
0.6004647612571716
0.5983507633209229
0.5962573289871216
0.5941842794418335
0.5921332836151123
0.5901018381118774
0.5880926251411438
0.5861039757728577

Inference

In [ ]:
ynewp = model(X)

In [ ]:
sftout = torch.softmax(ynewp,dim=1)

In [ ]:
torch.argmax(sftout, dim=1)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2])

Batches

In [81]:
from torch.utils.data import DataLoader

In [82]:
df = pd.DataFrame(X)

In [83]:
df

     0    1    2    3
0  5.7  3.8  1.7  0.3
1  6.9  3.2  5.7  2.3
2  6.0  2.2  5.0  1.5
3  5.5  4.2  1.4  0.2
4  6.3  3.3  4.7  1.6
5  6.3  3.4  5.6  2.4
6  6.7  3.3  5.7  2.5
7  5.7  2.6  3.5  1.0
8  6.0  3.0  4.8  1.8
9  5.2  4.1  1.5  0.1

In [ ]:
#[X,Y]

[tensor([[5.1000, 3.5000, 1.4000, 0.2000],
         [4.9000, 3.0000, 1.4000, 0.2000],
         [4.7000, 3.2000, 1.3000, 0.2000],
         [4.6000, 3.1000, 1.5000, 0.2000],
         [5.0000, 3.6000, 1.4000, 0.2000],
         [5.4000, 3.9000, 1.7000, 0.4000],
         [4.6000, 3.4000, 1.4000, 0.3000],
         [5.0000, 3.4000, 1.5000, 0.2000],
         [4.4000, 2.9000, 1.4000, 0.2000],
         [4.9000, 3.1000, 1.5000, 0.1000],
         [5.4000, 3.7000, 1.5000, 0.2000],
         [4.8000, 3.4000, 1.6000, 0.2000],
         [4.8000, 3.0000, 1.4000, 0.1000],
         [4.3000, 3.0000, 1.1000, 0.1000],
         [5.8000, 4.0000, 1.2000, 0.2000],
         [5.7000, 4.4000, 1.5000, 0.4000],
         [5.4000, 3.9000, 1.3000, 0.4000],
         [5.1000, 3.5000, 1.4000, 0.3000],
         [5.7000, 3.8000, 1.7000, 0.3000],
         [5.1000, 3.8000, 1.5000, 0.3000],
         [5.4000, 3.4000, 1.7000, 0.2000],
         [5.1000, 3.7000, 1.5000, 0.4000],
         [4.6000, 3.6000, 1.0000, 0.2000],
         [5.1000, 3.3000, 1.7000, 0.5000],
         [4.8000, 3.4000, 1.9000, 0.2000],
         [5.0000, 3.0000, 1.6000, 0.2000],
         [5.0000, 3.4000, 1.6000, 0.4000],
         [5.2000, 3.5000, 1.5000, 0.2000],
         [5.2000, 3.4000, 1.4000, 0.2000],
         [4.7000, 3.2000, 1.6000, 0.2000],
         [4.8000, 3.1000, 1.6000, 0.2000],
         [5.4000, 3.4000, 1.5000, 0.4000],
         [5.2000, 4.1000, 1.5000, 0.1000],
         [5.5000, 4.2000, 1.4000, 0.2000],
         [4.9000, 3.1000, 1.5000, 0.2000],
         [5.0000, 3.2000, 1.2000, 0.2000],
         [5.5000, 3.5000, 1.3000, 0.2000],
         [4.9000, 3.6000, 1.4000, 0.1000],
         [4.4000, 3.0000, 1.3000, 0.2000],
         [5.1000, 3.4000, 1.5000, 0.2000],
         [5.0000, 3.5000, 1.3000, 0.3000],
         [4.5000, 2.3000, 1.3000, 0.3000],
         [4.4000, 3.2000, 1.3000, 0.2000],
         [5.0000, 3.5000, 1.6000, 0.6000],
         [5.1000, 3.8000, 1.9000, 0.4000],
         [4.8000, 3.0000, 1.4000, 0.3000],
         [5.1000, 3.8000, 1.6000, 0.2000],
         [4.6000, 3.2000, 1.4000, 0.2000],
         [5.3000, 3.7000, 1.5000, 0.2000],
         [5.0000, 3.3000, 1.4000, 0.2000],
         [7.0000, 3.2000, 4.7000, 1.4000],
         [6.4000, 3.2000, 4.5000, 1.5000],
         [6.9000, 3.1000, 4.9000, 1.5000],
         [5.5000, 2.3000, 4.0000, 1.3000],
         [6.5000, 2.8000, 4.6000, 1.5000],
         [5.7000, 2.8000, 4.5000, 1.3000],
         [6.3000, 3.3000, 4.7000, 1.6000],
         [4.9000, 2.4000, 3.3000, 1.0000],
         [6.6000, 2.9000, 4.6000, 1.3000],
         [5.2000, 2.7000, 3.9000, 1.4000],
         [5.0000, 2.0000, 3.5000, 1.0000],
         [5.9000, 3.0000, 4.2000, 1.5000],
         [6.0000, 2.2000, 4.0000, 1.0000],
         [6.1000, 2.9000, 4.7000, 1.4000],
         [5.6000, 2.9000, 3.6000, 1.3000],
         [6.7000, 3.1000, 4.4000, 1.4000],
         [5.6000, 3.0000, 4.5000, 1.5000],
         [5.8000, 2.7000, 4.1000, 1.0000],
         [6.2000, 2.2000, 4.5000, 1.5000],
         [5.6000, 2.5000, 3.9000, 1.1000],
         [5.9000, 3.2000, 4.8000, 1.8000],
         [6.1000, 2.8000, 4.0000, 1.3000],
         [6.3000, 2.5000, 4.9000, 1.5000],
         [6.1000, 2.8000, 4.7000, 1.2000],
         [6.4000, 2.9000, 4.3000, 1.3000],
         [6.6000, 3.0000, 4.4000, 1.4000],
         [6.8000, 2.8000, 4.8000, 1.4000],
         [6.7000, 3.0000, 5.0000, 1.7000],
         [6.0000, 2.9000, 4.5000, 1.5000],
         [5.7000, 2.6000, 3.5000, 1.0000],
         [5.5000, 2.4000, 3.8000, 1.1000],
         [5.5000, 2.4000, 3.7000, 1.0000],
         [5.8000, 2.7000, 3.9000, 1.2000],
         [6.0000, 2.7000, 5.1000, 1.6000],
         [5.4000, 3.0000, 4.5000, 1.5000],
         [6.0000, 3.4000, 4.5000, 1.6000],
         [6.7000, 3.1000, 4.7000, 1.5000],
         [6.3000, 2.3000, 4.4000, 1.3000],
         [5.6000, 3.0000, 4.1000, 1.3000],
         [5.5000, 2.5000, 4.0000, 1.3000],
         [5.5000, 2.6000, 4.4000, 1.2000],
         [6.1000, 3.0000, 4.6000, 1.4000],
         [5.8000, 2.6000, 4.0000, 1.2000],
         [5.0000, 2.3000, 3.3000, 1.0000],
         [5.6000, 2.7000, 4.2000, 1.3000],
         [5.7000, 3.0000, 4.2000, 1.2000],
         [5.7000, 2.9000, 4.2000, 1.3000],
         [6.2000, 2.9000, 4.3000, 1.3000],
         [5.1000, 2.5000, 3.0000, 1.1000],
         [5.7000, 2.8000, 4.1000, 1.3000],
         [6.3000, 3.3000, 6.0000, 2.5000],
         [5.8000, 2.7000, 5.1000, 1.9000],
         [7.1000, 3.0000, 5.9000, 2.1000],
         [6.3000, 2.9000, 5.6000, 1.8000],
         [6.5000, 3.0000, 5.8000, 2.2000],
         [7.6000, 3.0000, 6.6000, 2.1000],
         [4.9000, 2.5000, 4.5000, 1.7000],
         [7.3000, 2.9000, 6.3000, 1.8000],
         [6.7000, 2.5000, 5.8000, 1.8000],
         [7.2000, 3.6000, 6.1000, 2.5000],
         [6.5000, 3.2000, 5.1000, 2.0000],
         [6.4000, 2.7000, 5.3000, 1.9000],
         [6.8000, 3.0000, 5.5000, 2.1000],
         [5.7000, 2.5000, 5.0000, 2.0000],
         [5.8000, 2.8000, 5.1000, 2.4000],
         [6.4000, 3.2000, 5.3000, 2.3000],
         [6.5000, 3.0000, 5.5000, 1.8000],
         [7.7000, 3.8000, 6.7000, 2.2000],
         [7.7000, 2.6000, 6.9000, 2.3000],
         [6.0000, 2.2000, 5.0000, 1.5000],
         [6.9000, 3.2000, 5.7000, 2.3000],
         [5.6000, 2.8000, 4.9000, 2.0000],
         [7.7000, 2.8000, 6.7000, 2.0000],
         [6.3000, 2.7000, 4.9000, 1.8000],
         [6.7000, 3.3000, 5.7000, 2.1000],
         [7.2000, 3.2000, 6.0000, 1.8000],
         [6.2000, 2.8000, 4.8000, 1.8000],
         [6.1000, 3.0000, 4.9000, 1.8000],
         [6.4000, 2.8000, 5.6000, 2.1000],
         [7.2000, 3.0000, 5.8000, 1.6000],
         [7.4000, 2.8000, 6.1000, 1.9000],
         [7.9000, 3.8000, 6.4000, 2.0000],
         [6.4000, 2.8000, 5.6000, 2.2000],
         [6.3000, 2.8000, 5.1000, 1.5000],
         [6.1000, 2.6000, 5.6000, 1.4000],
         [7.7000, 3.0000, 6.1000, 2.3000],
         [6.3000, 3.4000, 5.6000, 2.4000],
         [6.4000, 3.1000, 5.5000, 1.8000],
         [6.0000, 3.0000, 4.8000, 1.8000],
         [6.9000, 3.1000, 5.4000, 2.1000],
         [6.7000, 3.1000, 5.6000, 2.4000],
         [6.9000, 3.1000, 5.1000, 2.3000],
         [5.8000, 2.7000, 5.1000, 1.9000],
         [6.8000, 3.2000, 5.9000, 2.3000],
         [6.7000, 3.3000, 5.7000, 2.5000],
         [6.7000, 3.0000, 5.2000, 2.3000],
         [6.3000, 2.5000, 5.0000, 1.9000],
         [6.5000, 3.0000, 5.2000, 2.0000],
         [6.2000, 3.4000, 5.4000, 2.3000],
         [5.9000, 3.0000, 5.1000, 1.8000]]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         2, 2, 2, 2, 2, 2])]

In [84]:
df['Y'] = Y

In [85]:
data = torch.tensor(df.to_numpy())

In [86]:
batches = DataLoader(data, batch_size=10,shuffle = True)

In [87]:
for batch in batches:
  #print(batch)
  #batch = torch.tensor(batch)
  X = batch[:, :-1]
  Y = batch[:, -1]
  print(X,Y)

tensor([[6.3000, 3.4000, 5.6000, 2.4000],
        [6.3000, 3.3000, 4.7000, 1.6000],
        [6.9000, 3.2000, 5.7000, 2.3000],
        [6.7000, 3.3000, 5.7000, 2.5000],
        [5.2000, 4.1000, 1.5000, 0.1000],
        [5.5000, 4.2000, 1.4000, 0.2000],
        [5.7000, 2.6000, 3.5000, 1.0000],
        [5.7000, 3.8000, 1.7000, 0.3000],
        [6.0000, 3.0000, 4.8000, 1.8000],
        [6.0000, 2.2000, 5.0000, 1.5000]], dtype=torch.float64) tensor([2., 1., 2., 2., 0., 0., 1., 0., 2., 2.], dtype=torch.float64)

In [88]:
from torch.utils.data import DataLoader

In [89]:
df = pd.DataFrame(X)

In [90]:
df

     0    1    2    3
0  6.3  3.4  5.6  2.4
1  6.3  3.3  4.7  1.6
2  6.9  3.2  5.7  2.3
3  6.7  3.3  5.7  2.5
4  5.2  4.1  1.5  0.1
5  5.5  4.2  1.4  0.2
6  5.7  2.6  3.5  1.0
7  5.7  3.8  1.7  0.3
8  6.0  3.0  4.8  1.8
9  6.0  2.2  5.0  1.5

In [91]:
df['Y'] = Y

In [92]:
data = torch.tensor(df.to_numpy())

In [93]:
model1 = nn.Sequential (
    nn.Linear(4, 30),
    nn.ReLU(),
    nn.Linear(30, 10),
    nn.ReLU(),
    nn.Linear(10, 3),
    #nn.Softmax(dim = 1)
)

In [94]:
lossfn = nn.CrossEntropyLoss()
batchSgd1 = optim.SGD(model1.parameters(), lr =0.01)

In [72]:
batches = DataLoader(data, batch_size=10,shuffle = True)

In [98]:
model1.train()
for epoch in range(200):
  batch_loss = 0
  for i, batch in enumerate(batches):
    batch_X = batch[:, :-1].float()
    batch_Y = batch[:, -1].long()

    batchSgd1.zero_grad()
    batch_Yp = model1(batch_X)
    loss = lossfn(batch_Yp, batch_Y)
    loss.backward()
    batchSgd1.step()
    batch_loss = batch_loss + loss.item()
    print(f"Epoch {epoch+1}:  Total Loss = {batch_loss}")

Epoch 1:  Total Loss = 0.2587844729423523
Epoch 2:  Total Loss = 0.25816598534584045
Epoch 3:  Total Loss = 0.2575470209121704
Epoch 4:  Total Loss = 0.2569308876991272
Epoch 5:  Total Loss = 0.2563157379627228
Epoch 6:  Total Loss = 0.25570088624954224
Epoch 7:  Total Loss = 0.25508707761764526
Epoch 8:  Total Loss = 0.2544736862182617
Epoch 9:  Total Loss = 0.2538609802722931
Epoch 10:  Total Loss = 0.25324946641921997
Epoch 11:  Total Loss = 0.2526378333568573
Epoch 12:  Total Loss = 0.2520276606082916
Epoch 13:  Total Loss = 0.25141769647598267
Epoch 14:  Total Loss = 0.25080907344818115
Epoch 15:  Total Loss = 0.2502003014087677
Epoch 16:  Total Loss = 0.24959306418895721
Epoch 17:  Total Loss = 0.24898603558540344
Epoch 18:  Total Loss = 0.24838025867938995
Epoch 19:  Total Loss = 0.24777451157569885
Epoch 20:  Total Loss = 0.24717023968696594
Epoch 21:  Total Loss = 0.24656608700752258
Epoch 22:  Total Loss = 0.24596352875232697
Epoch 23:  Total Loss = 0.24536089599132538
Epoch 24:  Total Loss = 0.24475927650928497
Epoch 25:  Total Loss = 0.24415870010852814
Epoch 26:  Total Loss = 0.2435588836669922
Epoch 27:  Total Loss = 0.2429598569869995
Epoch 28:  Total Loss = 0.24236123263835907
Epoch 29:  Total Loss = 0.24176378548145294
Epoch 30:  Total Loss = 0.24116703867912292
Epoch 31:  Total Loss = 0.24057140946388245
Epoch 32:  Total Loss = 0.23997624218463898
Epoch 33:  Total Loss = 0.2393818199634552
Epoch 34:  Total Loss = 0.23878833651542664
Epoch 35:  Total Loss = 0.23819592595100403
Epoch 36:  Total Loss = 0.23760433495044708
Epoch 37:  Total Loss = 0.23701350390911102
Epoch 38:  Total Loss = 0.23642344772815704
Epoch 39:  Total Loss = 0.23583409190177917
Epoch 40:  Total Loss = 0.23524591326713562
Epoch 41:  Total Loss = 0.23465867340564728
Epoch 42:  Total Loss = 0.23407229781150818
Epoch 43:  Total Loss = 0.23348677158355713
Epoch 44:  Total Loss = 0.23290196061134338
Epoch 45:  Total Loss = 0.2323179990053177
Epoch 46:  Total Loss = 0.23173515498638153
Epoch 47:  Total Loss = 0.23115336894989014
Epoch 48:  Total Loss = 0.23057234287261963
Epoch 49:  Total Loss = 0.22999247908592224
Epoch 50:  Total Loss = 0.22941312193870544
Epoch 51:  Total Loss = 0.2288348376750946
Epoch 52:  Total Loss = 0.2282574474811554
Epoch 53:  Total Loss = 0.22768104076385498
Epoch 54:  Total Loss = 0.2271057665348053
Epoch 55:  Total Loss = 0.2265314757823944
Epoch 56:  Total Loss = 0.22595825791358948
Epoch 57:  Total Loss = 0.22538578510284424
Epoch 58:  Total Loss = 0.22481422126293182
Epoch 59:  Total Loss = 0.22424368560314178
Epoch 60:  Total Loss = 0.22367413341999054
Epoch 61:  Total Loss = 0.22310566902160645
Epoch 62:  Total Loss = 0.22253815829753876
Epoch 63:  Total Loss = 0.22197167575359344
Epoch 64:  Total Loss = 0.22140631079673767
Epoch 65:  Total Loss = 0.22084207832813263
Epoch 66:  Total Loss = 0.22027871012687683
Epoch 67:  Total Loss = 0.21971628069877625
Epoch 68:  Total Loss = 0.2191549837589264
Epoch 69:  Total Loss = 0.21859462559223175
Epoch 70:  Total Loss = 0.21803545951843262
Epoch 71:  Total Loss = 0.21748562157154083
Epoch 72:  Total Loss = 0.21693050861358643
Epoch 73:  Total Loss = 0.21638460457324982
Epoch 74:  Total Loss = 0.21583251655101776
Epoch 75:  Total Loss = 0.2152867317199707
Epoch 76:  Total Loss = 0.2147412747144699
Epoch 77:  Total Loss = 0.21419382095336914
Epoch 78:  Total Loss = 0.21365146338939667
Epoch 79:  Total Loss = 0.21310965716838837
Epoch 80:  Total Loss = 0.21256586909294128
Epoch 81:  Total Loss = 0.2120256870985031
Epoch 82:  Total Loss = 0.21148863434791565
Epoch 83:  Total Loss = 0.21094834804534912
Epoch 84:  Total Loss = 0.21041007339954376
Epoch 85:  Total Loss = 0.20987717807292938
Epoch 86:  Total Loss = 0.20934219658374786
Epoch 87:  Total Loss = 0.2088068723678589
Epoch 88:  Total Loss = 0.2082739770412445
Epoch 89:  Total Loss = 0.20774582028388977
Epoch 90:  Total Loss = 0.20721396803855896
Epoch 91:  Total Loss = 0.20668387413024902
Epoch 92:  Total Loss = 0.20615652203559875
Epoch 93:  Total Loss = 0.20563217997550964
Epoch 94:  Total Loss = 0.2051052302122116
Epoch 95:  Total Loss = 0.2045799195766449
Epoch 96:  Total Loss = 0.20405647158622742
Epoch 97:  Total Loss = 0.2035374939441681
Epoch 98:  Total Loss = 0.2030152827501297
Epoch 99:  Total Loss = 0.2024947851896286
Epoch 100:  Total Loss = 0.20197567343711853
Epoch 101:  Total Loss = 0.20145992934703827
Epoch 102:  Total Loss = 0.20094497501850128
Epoch 103:  Total Loss = 0.20042884349822998
Epoch 104:  Total Loss = 0.19991424679756165
Epoch 105:  Total Loss = 0.19940124452114105
Epoch 106:  Total Loss = 0.19889171421527863
Epoch 107:  Total Loss = 0.19838228821754456
Epoch 108:  Total Loss = 0.19787219166755676
Epoch 109:  Total Loss = 0.1973637193441391
Epoch 110:  Total Loss = 0.19685664772987366
Epoch 111:  Total Loss = 0.19635240733623505
Epoch 112:  Total Loss = 0.19584964215755463
Epoch 113:  Total Loss = 0.19534556567668915
Epoch 114:  Total Loss = 0.19484321773052216
Epoch 115:  Total Loss = 0.1943422108888626
Epoch 116:  Total Loss = 0.1938425600528717
Epoch 117:  Total Loss = 0.19334617257118225
Epoch 118:  Total Loss = 0.19284984469413757
Epoch 119:  Total Loss = 0.19235306978225708
Epoch 120:  Total Loss = 0.19185812771320343
Epoch 121:  Total Loss = 0.19136443734169006
Epoch 122:  Total Loss = 0.19087204337120056
Epoch 123:  Total Loss = 0.1903824657201767
Epoch 124:  Total Loss = 0.1898939311504364
Epoch 125:  Total Loss = 0.18940459191799164
Epoch 126:  Total Loss = 0.1889168918132782
Epoch 127:  Total Loss = 0.18843069672584534
Epoch 128:  Total Loss = 0.18794569373130798
Epoch 129:  Total Loss = 0.18746201694011688
Epoch 130:  Total Loss = 0.1869812309741974
Epoch 131:  Total Loss = 0.18650087714195251
Epoch 132:  Total Loss = 0.18602022528648376
Epoch 133:  Total Loss = 0.1855412721633911
Epoch 134:  Total Loss = 0.18506373465061188
Epoch 135:  Total Loss = 0.18458744883537292
Epoch 136:  Total Loss = 0.18411244451999664
Epoch 137:  Total Loss = 0.183639258146286
Epoch 138:  Total Loss = 0.18316850066184998
Epoch 139:  Total Loss = 0.18269659578800201
Epoch 140:  Total Loss = 0.18222638964653015
Epoch 141:  Total Loss = 0.1817575991153717
Epoch 142:  Total Loss = 0.18129006028175354
Epoch 143:  Total Loss = 0.18082378804683685
Epoch 144:  Total Loss = 0.1803588569164276
Epoch 145:  Total Loss = 0.1798950731754303
Epoch 146:  Total Loss = 0.17943362891674042
Epoch 147:  Total Loss = 0.17897340655326843
Epoch 148:  Total Loss = 0.1785127967596054
Epoch 149:  Total Loss = 0.17805388569831848
Epoch 150:  Total Loss = 0.17759640514850616
Epoch 151:  Total Loss = 0.17714008688926697
Epoch 152:  Total Loss = 0.1766851395368576
Epoch 153:  Total Loss = 0.17623145878314972
Epoch 154:  Total Loss = 0.17577901482582092
Epoch 155:  Total Loss = 0.17532792687416077
Epoch 156:  Total Loss = 0.17487984895706177
Epoch 157:  Total Loss = 0.17443051934242249
Epoch 158:  Total Loss = 0.17398293316364288
Epoch 159:  Total Loss = 0.1735367327928543
Epoch 160:  Total Loss = 0.1730917990207672
Epoch 161:  Total Loss = 0.1726481020450592
Epoch 162:  Total Loss = 0.17220577597618103
Epoch 163:  Total Loss = 0.17176462709903717
Epoch 164:  Total Loss = 0.17132489383220673
Epoch 165:  Total Loss = 0.17088624835014343
Epoch 166:  Total Loss = 0.1704488843679428
Epoch 167:  Total Loss = 0.1700131744146347
Epoch 168:  Total Loss = 0.16957953572273254
Epoch 169:  Total Loss = 0.16914542019367218
Epoch 170:  Total Loss = 0.16871294379234314
Epoch 171:  Total Loss = 0.16828176379203796
Epoch 172:  Total Loss = 0.1678520143032074
Epoch 173:  Total Loss = 0.16742335259914398
Epoch 174:  Total Loss = 0.16699613630771637
Epoch 175:  Total Loss = 0.1665700376033783
Epoch 176:  Total Loss = 0.16614529490470886
Epoch 177:  Total Loss = 0.16572165489196777
Epoch 178:  Total Loss = 0.1652994304895401
Epoch 179:  Total Loss = 0.16487851738929749
Epoch 180:  Total Loss = 0.16445861756801605
Epoch 181:  Total Loss = 0.16404010355472565
Epoch 182:  Total Loss = 0.16362416744232178
Epoch 183:  Total Loss = 0.163207545876503
Epoch 184:  Total Loss = 0.1627926379442215
Epoch 185:  Total Loss = 0.16237901151180267
Epoch 186:  Total Loss = 0.16196665167808533
Epoch 187:  Total Loss = 0.16155552864074707
Epoch 188:  Total Loss = 0.16114573180675507
Epoch 189:  Total Loss = 0.16073709726333618
Epoch 190:  Total Loss = 0.16032978892326355
Epoch 191:  Total Loss = 0.15992365777492523
Epoch 192:  Total Loss = 0.1595187485218048
Epoch 193:  Total Loss = 0.15911510586738586
Epoch 194:  Total Loss = 0.1587127447128296
Epoch 195:  Total Loss = 0.15831153094768524
Epoch 196:  Total Loss = 0.15791158378124237
Epoch 197:  Total Loss = 0.1575128734111786
Epoch 198:  Total Loss = 0.15711544454097748
Epoch 199:  Total Loss = 0.15671920776367188
Epoch 200:  Total Loss = 0.156324103474617